package com.student.management.model;

/**
 * Domain model representing a single Student entity.
 * Instances of this class are populated from database query results
 * and utilized throughout the application layer for reporting and console display.
 */
public class Student
{
    // Unique identifier, automatically generated by the database
    private int id;
    
    // Full name of the student
    private String name;
    
    // Age of the student (validated range: 5 to 120)
    private int age;
    
    // Academic grade achieved (validated options: O, E, A, B, C, D, or F)
    private String grade;

    /**
     * Constructs an immutable model representation of a Student record.
     *
     * @param id    Unique database student ID
     * @param name  The full name of the student
     * @param age   The student's age
     * @param grade The academic grade assigned to the student
     */
    public Student(int id, String name, int age, String grade)
    {
        this.id = id;
        this.name = name;
        this.age = age;
        this.grade = grade;
    }

    // ===== Getters for retrieving Student properties =====

    public int getId()
    {
        return id;
    }

    public String getName()
    {
        return name;
    }

    public int getAge()
    {
        return age;
    }

    public String getGrade()
    {
        return grade;
    }


    /**
     * Generates a premium ASCII-box formatted string to display the student details in the console.
     *
     * @return Formatted student information within a styled console card
     */
    @Override
    public String toString()
    {
        return String.format(
                """
                        ┌─────────────────────────────┐
                        │    📚 Student Information   │
                        ├─────────────────────────────┤
                        │ ID    : %-20d │
                        │ Name  : %-20s │
                        │ Age   : %-20d │
                        │ Grade : %-20s │
                        └─────────────────────────────┘
                        """, id, name, age, grade);
    }
}
